name: GitHub-Profile-Summary-Cards

on:
  create:
  push:
  schedule: # 毎日JST0時 のはず
    - cron: "0 15 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate

    steps:
      - uses: actions/checkout@v4
      - uses: everyonelovesyou/github-profile-summary-cards@main
        env:
          GITHUB_TOKEN: ${{ secrets.SUMMARY_CARDS_TOKEN }}
        with:
          USERNAME: ${{ github.repository_owner }}
          UTC_OFFSET: 9
          EXCLUDE: "Roff"
